
# General
name: genet_large_512_hard_arcface_gem_64_05_ema
# name: debug
seed: 42
root: data/interim
batch_size: 48
workers: 5
augmentation: hard
debug: false
resume: ""
head_warmup_epochs: 2

# Model
arch: genet_large
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.99
freeze_bn: false

# Training
optim: adamw
use_fp16: true
weight_decay: 0.001
size: 512
val_size: 640
phases: [
    {ep: [0, 4], lr: [0, 0.001]}, # warmup
    {ep: [4, 25], lr: [0.001, 0.00001]},
]
criterion: arcface
criterion_params: {out_features: 3097, s: 64.0, m: 0.5}