
# General
name: genet_normal_384_light_arcface64_05
# name: debug
seed: 42
root: data/interim
batch_size: 64
workers: 6
augmentation: light
debug: false
resume: ""
head_warmup_epochs: 1

# Model
arch: genet_normal
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.0
freeze_bn: false

# Training
optim: adamw
use_fp16: true
weight_decay: 0.001
size: 384
val_size: 512
phases: [
    {ep: [0, 3], lr: [0, 0.001]}, # warmup
    {ep: [3, 20], lr: [0.001, 0.00001], mode: cos},
]
criterion: arcface
criterion_params: {out_features: 3097, s: 64.0, m: 0.5}