
# General
name: genet_small_384_light_arcface80_1
seed: 42
root: data/interim
batch_size: 128
workers: 6
augmentation: light
debug: false
resume: ""

# Model
arch: genet_small
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.0
freeze_bn: false

# Training
optim: adamw
use_fp16: true
weight_decay: 0.00001
size: 384
val_size: 512
phases: [
    {ep: [0, 20], lr: [0.01,0.0001]},
]
criterion: arcface
criterion_params: {out_features: 3097, s: 80.0, m: 1.0}