
# General
name: genet_normal_384_hard_arcface100_20
seed: 42
root: data/interim
batch_size: 64
workers: 6
augmentation: hard
debug: false
resume: ""

# Model
arch: genet_normal
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.0
freeze_bn: false

# Training
optim: adamw
use_fp16: true
weight_decay: 0.00001
size: 384
val_size: 512
phases: [
    {ep: [0, 10], lr: [0.000001,0.01]},
    {ep: [10, 100], lr: [0.01,0.00001]},
]
criterion: arcface
criterion_params: {out_features: 3097, s: 100.0, m: 20.0}