
# General
name: genet_normal_384_hard_arcface80_15
# name: debug
seed: 42
root: data/interim
batch_size: 64
workers: 6
augmentation: hard
debug: false
resume: "logs/genet_normal_384_light_arcface64_05/model.chpn"
head_warmup_epochs: 0

# Model
arch: genet_normal
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.0
freeze_bn: false

# Training
optim: adamw
use_fp16: true
weight_decay: 0.001
size: 384
val_size: 512
phases: [
    {ep: [0, 3], lr: [0, 0.0005]}, # warmup
    {ep: [3, 30], lr: [0.0005, 0], mode: cos},
]
criterion: arcface
criterion_params: {out_features: 3097, s: 80.0, m: 15}