
# General
name: genet_small_512_hard_arcface80
seed: 42
root: data/interim
batch_size: 96
workers: 10
augmentation: hard
debug: false
resume: logs/genet_small_512_light_arcface80

# Model
arch: genet_small
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.0
freeze_bn: false

# Training
optim: adamw
use_fp16: true
weight_decay: 0.00001
size: 512
val_size: 768
phases: [
    {ep: [0, 30], lr: [0.001,0.00001]},
]
criterion: arcface
criterion_params: {out_features: 3097, s: 80.0, m: 1.0}