
# General
name: genet_small_384_hard_arcface80_20
seed: 42
root: data/interim
batch_size: 96
workers: 6
augmentation: hard
debug: false
resume: logs/genet_small_384_light_arcface80_20/model.chpn

# Model
arch: genet_small
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.0
freeze_bn: false

# Training
optim: adamw
use_fp16: true
weight_decay: 0.00001
size: 384
val_size: 512
phases: [
    {ep: [0, 1], lr: [0.000001,0.001]},
    {ep: [1, 30], lr: [0.001,0.00001]},
]
criterion: arcface
criterion_params: {out_features: 3097, s: 80.0, m: 20.0}