
# General
name: genet_normal_512_hard_arcface80_15_reduced_focal
# name: debug
seed: 42
root: data/interim
batch_size: 32
workers: 5
augmentation: hard
debug: false
resume: "logs/genet_normal_384_hard_arcface80_15/model.chpn"
head_warmup_epochs: 0

# Model
arch: genet_normal
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.99
freeze_bn: false

# Training
optim: adamw
use_fp16: true
weight_decay: 0.001
size: 512
val_size: 768
phases: [
    {ep: [0, 3], lr: [0.00001, 0.001], mode: cos}, # warmup
    {ep: [3, 40], lr: [0.001, 0.00001], mode: cos},
]
criterion: arcface
criterion_params: {out_features: 3097, s: 80.0, m: 15.0, criterion: reduced_focal}