
# General
name: default
seed: 42
root: data/interim
batch_size: 32
workers: 6
augmentation: light
debug: false
resume: ""

# Model
arch: resnet50
model_params: {}
embedding_size: 512
ema_decay: 0.0

# Training
optim: adamw
use_fp16: false
weight_decay: 0.00001
size: 768
phases: [
    {'ep':[0, 10], 'lr': [0.001,0.00001], size: 256, val_size: 256},
]

criterion: cosface
criterion_params: {out_features: 3097, s: null, m: null, criterion: cross_entropy}

# Validation and testing
val_frequency: 1
val_size: 768
tta: false