
# General
name: default
seed: 42
root: data/raw
batch_size: 32
workers: 6
augmentation: light
debug: false
resume: ""

# Model
arch: resnet18
model_params: {}
embedding_size: 512
ema_decay: 0.0

# Training
optim: adam
opt_level: O0
weight_decay: 0.00001
size: 512
phases: [
    {'ep':[0, 10], 'lr': [0.001,0.00001], pos_weight: 0.08, size: 256, val_size: 256},
]

criterion: cosface
criterion_params: {in_features: 512, out_features: 3097, s: null, m: null}

# Validation and testing
val_frequency: 1
val_size: 512
tta: false