
# General
# name: debug
name: genet_normal_512_arcface_fp16_gem_light
seed: 42
root: data/interim
batch_size: 96
workers: 6
augmentation: light
debug: false
resume: ""

# Model
arch: genet_normal
pooling: gem
model_params: {}
embedding_size: 512
ema_decay: 0.0

# Training
optim: adamw
use_fp16: true
weight_decay: 0.00001
size: 512
phases: [
    {ep: [0, 50], lr: [0.05,0.00001], mode: 'cos'}
]

criterion: arcface
criterion_params: {out_features: 3097, s: 64.0, m: 0.5}

# Validation and testing
val_size: 768
tta: false