
# General
# name: debug
name: resnet50_384_arcface_fp16
seed: 42
root: data/interim
batch_size: 64
workers: 6
augmentation: light
debug: false
resume: ""

# Model
arch: resnet50
model_params: {}
embedding_size: 512
ema_decay: 0.0

# Training
optim: adamw
use_fp16: true
weight_decay: 0.00001
size: 384
phases: [
    {'ep':[0, 20], 'lr': [0.001,0.00001]}
]

criterion: arcface
criterion_params: {out_features: 3097, s: 64.0, m: 0.3}

# Validation and testing
val_size: 768
tta: false