
# General
name: debug
# name: baseline_resnet34_384_arcface
seed: 42
root: data/interim
batch_size: 32
workers: 6
augmentation: light
debug: true
resume: ""

# Model
arch: resnet34
pooling: avg
model_params: {}
embedding_size: 512
ema_decay: 0.0

# Training
optim: adamw
use_fp16: true
weight_decay: 0.00001
size: 384
phases: [
    {'ep':[0, 20], 'lr': [0.001,0.00001]}
]

criterion: cosface
criterion_params: {out_features: 3097, s: 64.0, m: 0.3}

# Validation and testing
val_size: 768
tta: false