
# General
name: baseline_resnet50_arcface
seed: 42
root: data/interim
batch_size: 24
workers: 6
augmentation: light
debug: false
resume: ""

# Model
arch: resnet50
model_params: {}
embedding_size: 512
ema_decay: 0.0

# Training
optim: adamw
opt_level: O0
weight_decay: 0.00001
size: 768
phases: [
    {'ep':[0, 10], 'lr': [0.001,0.00001]},
]

criterion: arcface
criterion_params: {out_features: 3097, s: null, m: null}

# Validation and testing
val_frequency: 1
val_size: 768
tta: false